const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const multer = require('multer');
const { PDFParse, VerbosityLevel } = require('pdf-parse');
require('dotenv').config();

const app = express();
const port = process.env.PORT || 3001;

app.use(helmet());
app.use(cors());
app.use(express.json());

const upload = multer({ 
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 } // 10MB limit
});

/**
 * Parse a PDF buffer and return extracted text using pdf-parse v2
 * @param {Buffer} buffer
 * @returns {Promise<string>}
 */
const extractPdfText = async (buffer) => {
  const parser = new PDFParse({ verbosity: VerbosityLevel.ERRORS });
  const result = await parser.load(buffer);
  let text = '';
  for (let i = 1; i <= result.numPages; i++) {
    const page = await parser.getText(i);
    text += page.text + '\n\n';
  }
  return text;
};

// Mock AI clause analyzer (used when no real LLM API key is set)
const analyzeClauses = async (text, locale) => {
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  let paragraphs = text.split(/\n\n+/).filter(p => p.trim().length > 20).slice(0, 5);
  
  // Fallback sample clauses if PDF has no readable text
  if (paragraphs.length === 0) {
    paragraphs = [
      'The tenant shall pay all maintenance costs without limitation.',
      'The landlord reserves the right to modify the terms at any time without prior notice.',
      'Disputes shall be resolved exclusively by arbitration chosen by the landlord.'
    ];
  }

  const riskLevels = ['low', 'medium', 'high'];

  return paragraphs.map((clauseText, index) => {
    const risk = riskLevels[index % 3];
    return {
      id: `clause-${index}`,
      text: clauseText.trim(),
      risk_level: risk,
      plain_explanation: locale === 'es' 
        ? `Explicación simulada para cláusula de riesgo ${risk}.` 
        : `Simulated explanation for a ${risk} risk clause.`,
      legal_reasoning: locale === 'es'
        ? 'Evaluación generada por el servicio de simulación (sin API key real configurada).'
        : 'Evaluation generated by the mock service (no real API key configured).'
    };
  });
};

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok' });
});

app.post('/api/contracts/analyze', upload.single('contract'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file uploaded' });
    }

    const locale = req.body.locale || 'en';
    let extractedText = '';

    if (req.file.mimetype === 'application/pdf') {
      extractedText = await extractPdfText(req.file.buffer);
    } else {
      // Image: In production this would go to a multimodal LLM
      extractedText = 'Mocked OCR text from image.\n\nAnother paragraph from image.\n\nA risky abusive clause with hidden fees and penalties without limit.';
    }

    const clauses = await analyzeClauses(extractedText, locale);
    
    // Weighted risk score: high=30pts, medium=10pts, capped at 100
    let score = 0;
    clauses.forEach(c => {
      if (c.risk_level === 'high') score += 30;
      if (c.risk_level === 'medium') score += 10;
    });
    const global_risk_score = Math.min(100, score);

    res.json({ id: 'mock-contract-123', global_risk_score, clauses });

  } catch (error) {
    console.error('Error analyzing contract:', error);
    res.status(500).json({ error: 'Internal server error', details: error.message });
  }
});

app.listen(port, () => {
  console.log(`Backend server running on port ${port}`);
});
